### ISSUE TITLE
How to add google calendar sync to my app?

### ISSUE THREAD

**Issue by ghost** [SwitchbackTech/compass#103]
Hi, Tyler. Just found this app, it's really amazing. I appreciate your work.

I always admired Todoist for having 2 way sync with google calendae which no other app does. Finding someone who achieved the same thing feels so good:) Thank you for open sourcing it.

MY QUESTION:
I would love to ask for your guidance if you have some time. So I am making todo list app with Nextjs and Clerk for Auth. Users can integrate their google calendar afterwards if they want to, and their tasks will be synced to their google calendar.

So could you please guide me on how I should do it, what part of your codebase I should focus on reading, etc.? Thank you very much:)

**Comment by tyler-dane** [comment]
Hey @terlan4 , thank you for the kind words. 

You're in for some fun. I've been gatekeeping my internal doc about how the sync stuff works. This felt like a good reason to finally make it public. Here it is: https://docs.compasscalendar.com/docs/advanced/Auth%20+%20Sync 

This is the directory with most of the sync-related code: https://github.com/SwitchbackTech/compass/tree/main/packages/backend/src/sync

**Comment by tyler-dane** [comment]
Hey @terlan4, thanks for the kudos! 
I've definitely thought about the sync-as-a-service idea. Although I don't currently have the bandwidth to make it, I could see how creating a better syncing API could save teams a lot of time. Maybe you can create that :) 

Re: resources that'll help you understand the code:
- [Synchronize resources efficiently](https://developers.google.com/calendar/api/guides/sync) by Google provides a high-level overview
- Anything that covers a Microservice architecture, especially the difference between services and controllers
