### ISSUE TITLE
Setup Redirect Rules and 404 Component

### ISSUE THREAD

**Issue by xypnox** [SwitchbackTech/compass#11]
## Expected Behavior

When visiting a route, such as [https://app.compasscalendar.com/login](https://app.compasscalendar.com/login), it should redirect to the index page due to being a SPA (Single Page App). 

## Current Behavior

Shows a 404 page.

## Steps to Reproduce

1. Open [https://app.compasscalendar.com/login](https://app.compasscalendar.com/login)

## Possible Solution (Not obligatory)

Redirect all pages to index * -> /

## Context

Loading a route or refreshing a page will cause a 404.

**Comment by tyler-dane** [comment]
Hey @xypnox , thanks for taking the time to document this. This is definitely a bug, and one that I believe many new users run into, which turns them away before they can get started. 

I'm currently pausing my development on this project, but I'd welcome and manually test any PRs that can implement a fix.

**Comment by xypnox** [comment]
I think it is a problem with the nginx config which I cannot find in the repo.

Here is the stackoverflow answer with similar forwarding issue: https://stackoverflow.com/a/43954597/

The solution seems to be configuring nginx to redirect all requests to index.html.

```
location / {
  try_files $uri /index.html;
}
```

**Comment by tyler-dane** [comment]
Ah, I think you're right about needing to change the nginx configs on the server. 

And yes, the nginx config files are not in this repo. 

If I'm ever making changes to the server config in the future, I'll try that redirect out and update this issue.
