### ISSUE TITLE
Date Picker doesn't close after selecting date

### ISSUE THREAD

**Issue by tyler-dane** [SwitchbackTech/compass#131]
## Prerequisites

- [x] Using an up-to-date main branch

## Expected Behavior
After selecting a date from the datepicker, the date picker should close and the selected date should appear in the date field

## Current Behavior
After selecting a date from the datepicker, the date picker flashes and stays open

## Steps to Reproduce
1. Click all-day row, which triggers event form to render

2. Click start or end date, which triggers date picker to render

3. Select a date from the datepicker

## Possible Solution (Not obligatory)
I assume this is because we're re-rendering the form unnecessarily. Refactor the form/datepicker so that it doesn't need to rerender after changing the date

**Comment by murilo9** [comment]
May I work on this one?

**Comment by tyler-dane** [comment]
You bet! Assigned it to you and marked In Progress
