### ISSUE TITLE
Make header labels more accurate

### ISSUE THREAD

**Issue by tyler-dane** [SwitchbackTech/compass#165]
The current, somewhat-confusing labels:
![Image](https://github.com/user-attachments/assets/69546913-0675-46be-8809-b69d0b5f8f66)

Rules
1. Display the month when viewing a week that is entirely in the current year
2. Display the the month+year when viewing a previous/future year
3. When viewing a week that spans multiple years, display the label in the format of `{Short Month} {Short Year} - {Short Month} {Short year}`

## Acceptance Criteria

- [ ] All labels follow the above rules
- [ ] Unit test(s) provided that validate each rule

Here is a reference table for all scenarios:

| Today    | Week In View | Heading label | Someday Week label | Someday Month label |
| -------- | ------- | ---- | ---- |---- |
| 1/8/25  | 1/5/25 - 1/11/25    | January | 1.5-11 | January |
| 12/30/24  | 1/5/25 - 1/11/25    | January 2025 | 1.5-11 | January |
| 12/30/24  | 12/29/24 - 1/4/25    | Dec 24 - Jan 25 | 12.29 - 1.4 | December |

## Context
Since Compass is a minimal calendar, this should help us minimize the text on the screen while also making it clear what dates the user is currently viewing

## Implementation Guidance
To confirm how it looks in the UI, you can hard-code the `today` value to in `useToday.ts` like so:
```typescript
const today = dayjs("2024-01-04");
```

**Comment by murilo9** [comment]
I'll be working on this one.
