### ISSUE TITLE
Remove ability to manually hide times from individual events

### ISSUE THREAD

**Issue by tyler-dane** [SwitchbackTech/compass#170]
I added an experimental feature that lets a user hover over the times and click them, which results in the times being hidden. Since this is not a popular feature, it is not worth maintaining the code to keep it working.

However, there is a similar feature that automatically hides the time labels for events in the past. This feature should be preserved.

### Implementation Guidance
1. Remove the `isTimesShown` property from the data model and all other files when possible (eg. mocks). You do not need to create a DB migration to remove this from existing events for users, though (I'll do this part afterwards)
3. Remove the CSS that renders the border around the times label upon hover
4. Remove the `onClick` handler on the event label 
### Acceptance Criteria
- [ ] User cannot hide times manually
- [ ] Times are still hidden automatically when event is in the past

**Comment by murilo9** [comment]
I will work on this one.
