### ISSUE TITLE
Integration with Capcaitor for mobile build

### ISSUE THREAD

**Issue by murilo9** [SwitchbackTech/compass#172]
That may likely not be a priority in the moment, but we could integrate [Capacitor](https://capacitorjs.com/) in the codebase so we could easily have Android and iOS builds. As Capacitor basically wraps the web build inside a native shell (and provides APIs for using native phone features like cameras, GPS, etc) we would essentially not need to have any change in the codebase (only some changes in the project's configuration).

**Comment by tyler-dane** [comment]
Thanks for the suggestion and link. Capacitor seems cool.

Adding mobile support is not a priority. I want to stay laser-focused on making Compass a great web product before adding more platforms. Even though we might not need to make code changes, the QA and deployment burden would increase. The barrier to entry for new devs also increases. I'd rather use that time to improve the existing web product until we have more resources. 

Closing this for now, but noting it for the future
