### ISSUE TITLE
Event saved with wrong time when drag and dropping from sidebar

### ISSUE THREAD

**Issue by tyler-dane** [SwitchbackTech/compass#190]
## Prerequisites

- [x] Using an up-to-date main branch

## Expected Behavior
GIVEN that a user has their mouse pressed and positioned over the grid
AND the preview event rectangle is rendered at the correct position
AND the preview event shows the desired correct time (eg `10 am`) 
AND the user releases the mouse
THEN an event rectangle is immediately displayed on the grid
AND the event time is the same as when the mouse was released

 
## Current Behavior
If a user continues to move their mouse after they drop and between the time when it was saved on the backend, then the start and end dates will be based on their most recent mouse position -- not their original. 

Notice: I release the mouse on Friday, then move over to Sunday. The event is saved as Tuesday 🙈

https://github.com/user-attachments/assets/48e9c7e4-5ab0-4de2-97a7-c98c19b52de3

## Steps to Reproduce

1. Create a sidebar event

2. Click the event and drag it over the grid

3. Note the day and time of the event

4. Release your mouse, while quickly moving it to the left or right
5. Notice: the event is saved at the latest mouse position, not the mouse position when you released it

## Possible Solution (Not obligatory)

We need a way to accurately capture the desired date/time at the time of mousing up, rather than relying on the mouse position's X/Y coordinates, which can change during the API request's lifecycle. 

## Context
This makes users frustrated, because what is saved in the UI doesn't match their intentions.

**Comment by that-one-arab** [comment]
Assign me this please

**Comment by tyler-dane** [comment]
> Assign me this please

Assigned!
