### ISSUE TITLE
Event can still be changed during optimistic render

### ISSUE THREAD

**Issue by tyler-dane** [SwitchbackTech/compass#201]
### Where did this happen?

Local code with an up-to-date main branch

### Expected Behavior

An event shouldn't be allowed to be edited or deleted while it is being rendered optimistically

### Current Behavior

During the timespan where the optimistically generated event is created and the HTTP request returns a response from the server:

The event cannot be drag and dropped
The event cannot be deleted (would delete a local version but the API would re-generate a new one after the HTTP request returns a response)

### Steps to Reproduce

1. Create Event
2. Change event
3. While event change is being processed on backend, change the event again

### Possible Solution

Prevent the changes while an event is optimistically rendered

### Context

#197 introduced optimistic rendering.

**Comment by that-one-arab** [comment]
Assign me this please
