### ISSUE TITLE
User Forced to Go Through Login Flow Twice After Google Prompts for Full Sync

### ISSUE THREAD

**Issue by tyler-dane** [SwitchbackTech/compass#83]
## Prerequisites

- [x] Using an up-to-date main branch

## Expected Behavior
1. User tries to access Compass after the following occurs:
    - They haven't used Compass for an extended period of time
    - Compass cancels their sync and deletes their  data (events, user, priorities)
    - The user's session is still preserved in the browser
2. User redirected to login screen
3. User presses login button, prompting Oauth dialog
4. User confirms Oauth dialog
5. User's sync is initialized
6. Compass redirects to home page
7. User can access and edit events like normal

## Current Behavior
1-4 same
5:  Compass uses existing user account to start sync
  - Backend finds user and tries to do incremental import (`auth.controller:login:syncService.importIncremental())`
  - Google API responds with an error response that a full sync is required
  - Error is caught in `error.express.handler` and parsed
  - Error is determined to be one that requires a full sync
  - Compass obliges, starting a new full sync (`user.service:resyncGoogleData()`)
  - As part of the full sync, user's sessions are revoked ** (including the session they just created during login)

6: Compass redirects to home page, which triggers requests for `/api/event....`
7: The request fail with 401 unauthorized from SuperTokens

- This is because the user _had_ a valid session after clicking login, but that session was revoked by the backend
- This step doesn't cause issues if the user's session is still active. But if not, it fails during the `verifySession()` backend middleware

8: User is redirected to login page
9: User clicks through sign in button and dialog AGAIN
  - This time they go through the normal login flow (without doing a full-sync)
  
10: User is redirected to home page
11: User can finally access and edit events like normal

## Steps to Reproduce
Replicate scenario where the browser's session is out-of-date after doing a full-sync:
- TBD
- Is there a way to automatically update the browser session afterwards as part of the /api/oauth/google response?

Replicate scenario where Google receives syncToken and returns response that a full sync is required:
- logout
- change sync token value
- try logging in

Test scenario where user doesn't have sync record:
- delete a user's record for: `sync.google.events.syncToken`
- try signing in/up

----

Here's what the devtools like after 'successfully' going through the OAuth flow. Notice the 401 'unauthorised' message from Supertokens. 
![401s](https://github.com/user-attachments/assets/be4a8ff5-b62d-489a-8e31-c7132eb6103d)

Here are the logs that accompany the above scenario:

```bash
# tries to access events, 401 correctly return (session expired)
68|backend  | 401 GET /api/event?start=2024-03-03T00:00:00-06:00&end=2024-03-09T23:59:59-06:00 154.687ms Sat, 09 Mar 2024 21:01:24 GMT
68|backend  | 401 GET /api/event?someday=true&start=2024-03-01&end=2024-03-31 148.039ms Sat, 09 Mar 2024 21:01:24 GMT
68|backend  | 401 GET /api/event?start=2024-03-03T00:00:00-06:00&end=2024-03-09T23:59:59-06:00 1.188ms Sat, 09 Mar 2024 21:01:24 GMT
68|backend  | 401 GET /api/event?someday=true&start=2024-03-01&end=2024-03-31 1.079ms Sat, 09 Mar 2024 21:01:24 GMT
68|backend  | 401 GET /api/event?start=2024-03-03T00:00:00-06:00&end=2024-03-09T23:59:59-06:00 1.112ms Sat, 09 Mar 2024 21:01:24 GMT
68|backend  | 401 GET /api/event?someday=true&start=2024-03-01&end=2024-03-31 0.927ms Sat, 09 Mar 2024 21:01:24 GMT
68|backend  | 401 GET /api/event?start=2024-03-03T00:00:00-06:00&end=2024-03-09T23:59:59-06:00 0.744ms Sat, 09 Mar 2024 21:01:25 GMT
68|backend  | 401 GET /api/event?someday=true&start=2024-03-01&end=2024-03-31 0.681ms Sat, 09 Mar 2024 21:01:25 GMT
68|backend  | 401 GET /api/event?start=2024-03-03T00:00:00-06:00&end=2024-03-09T23:59:59-06:00 0.708ms Sat, 09 Mar 2024 21:01:25 GMT
68|backend  | 401 GET /api/event?someday=true&start=2024-03-01&end=2024-03-31 0.650ms Sat, 09 Mar 2024 21:01:25 GMT

# after going through oauth dialog box
68|backend  | 24-03-09 21:01:41 [debug] app:sync.helpers: REMINDER: Channel will expire in 7200 minutes (5 days)
68|backend  | 24-03-09 21:01:41 [warn] app:user.service: Re-syncing google data for user: 651488733aa260d5183921c1
68|backend  | 24-03-09 21:01:41 [debug] app:sync.service: Stopping all gcal event watches for user: 651488733aa260d5183921c1
68|backend  | 24-03-09 21:01:41 [debug] app:sync.service: Skipped stop for calendarId: test1@gmail.com due to missing field(s):
68|backend  |             channelId: undefined
68|backend  |             resourceid: eRqPWi.....
68|backend  | 24-03-09 21:01:42 [debug] app:sync.helpers: REMINDER: Channel will expire in 7200 minutes (5 days)
68|backend  | 24-03-09 21:01:42 [info] app:sync.service: Sync initialized for channelId: a4c00712-85d1-......
68|backend  | 200 POST /api/sync/gcal/notifications 0.829ms Sat, 09 Mar 2024 21:01:42 GMT
68|backend  | 200 POST /api/oauth/google 1814.245ms Sat, 09 Mar 2024 21:01:43 GMT

# but the next request still fails with the same 401 error (why???)
68|backend  | 401 GET /api/event?start=2024-03-03T00:00:00-06:00&end=2024-03-09T23:59:59-06:00 0.862ms Sat, 09 Mar 2024 21:01:43 GMT
68|backend  | 401 GET /api/event?someday=true&start=2024-03-01&end=2024-03-31 0.620ms Sat, 09 Mar 2024 21:01:43 GMT
68|backend  | 401 GET /api/event?start=2024-03-03T00:00:00-06:00&end=2024-03-09T23:59:59-06:00 0.634ms Sat, 09 Mar 2024 21:01:43 GMT
68|backend  | 401 GET /api/event?someday=true&start=2024-03-01&end=2024-03-31 0.584ms Sat, 09 Mar 2024 21:01:43 GMT
68|backend  | 401 GET /api/event?start=2024-03-03T00:00:00-06:00&end=2024-03-09T23:59:59-06:00 0.683ms Sat, 09 Mar 2024 21:02:10 GMT
68|backend  | 401 GET /api/event?start=2024-03-03T00:00:00-06:00&end=2024-03-09T23:59:59-06:00 0.781ms Sat, 09 Mar 2024 21:02:10 GMT
68|backend  | 401 GET /api/event?someday=true&start=2024-03-01&end=2024-03-31 0.587ms Sat, 09 Mar 2024 21:02:10 GMT
68|backend  | 401 GET /api/event?someday=true&start=2024-03-01&end=2024-03-31 0.600ms Sat, 09 Mar 2024 21:02:10 GMT

# creating an event in Google Calendar is triggered (ie, the sync is setup correctly)
68|backend  | 24-03-09 21:02:24 [debug] app:sync.service.helpers: updating: "synced?"  | eRq......
68|backend  | 200 POST /api/sync/gcal/notifications 248.032ms Sat, 09 Mar 2024 21:02:24 GMT

# user goes through Oauth again
68|backend  | 200 POST /api/oauth/google 743.598ms Sat, 09 Mar 2024 21:07:03 GMT

# now it works
68|backend  | 200 GET /api/event?start=2024-03-03T00:00:00-06:00&end=2024-03-09T23:59:59-06:00 111.797ms Sat, 09 Mar 2024 21:07:03 GMT
68|backend  | 200 GET /api/event?start=2024-03-03T00:00:00-06:00&end=2024-03-09T23:59:59-06:00 42.320ms Sat, 09 Mar 2024 21:07:03 GMT
68|backend  | 200 GET /api/event?someday=true&start=2024-03-01&end=2024-03-31 36.655ms Sat, 09 Mar 2024 21:07:03 GMT
68|backend  | 200 GET /api/event?someday=true&start=2024-03-01&end=2024-03-31 33.446ms Sat, 09 Mar 2024 21:07:03 GMT
68|backend  | 200 GET /api/event?start=2024-03-03T00:00:00-06:00&end=2024-03-09T23:59:59-06:00 16.417ms Sat, 09 Mar 2024 21:07:03 GMT
68|backend  | 200 GET /api/event?someday=true&start=2024-03-01&end=2024-03-31 12.486ms Sat, 09 Mar 2024 21:07:03 GMT
```

More backend logs, this time as a screenshot:
![401s-backend](https://github.com/user-attachments/assets/bcfea3e5-93e3-4207-9413-6060e2acea73)

## Causes
1) Compass is trying to use the nonexist fields: `sync.google.events.channeld` and/or `sync.google.events.nextSyncToken`
2) The user session is revoked as part of the auth process (see above)

### Extract the session revoking part from the resyncing Google data. 
This would fix cause 2

There are 3 scenarios when a user's Google data would need to be resynced:
  1. The user revoked access to Google Calendar
  2. The user deleted their data manually via Compass' CLI
  3. The user's data was pruned by Compass due to prolonged inactivity

Scenarios 1-2 should revoke the user's session after data cleanup.
Senario 3 doesn't need to revoke the session (cause of this bug). 
- This is because the user might've just created the session as part of their login

### Change the order of operations during this scenario:
- Don't create the user session on the until after successfully logging in/signing up (as result of request to `/api/oauth/google`)

### Handle Edge Case: Don't do incremental import in this scenario 
This would fix cause 1

The error happens when trying to do incremental import with Google, even though the sync has already been disconnected. It's not possible for us to know if Google with reject a syncToken. But we know they'll reject a null sync token, so don't even both trying to login if the token is missing.

## Context
This affects users by giving them the impression that the sign in is broken (it kinda is), which causes them to give up before trying again a second time.

**Comment by DiegoMutre** [comment]
Hey @tyler-dane 👋, I'm interested on this issue. How can I reproduce the scenario? Should I create a new account? When does the session expire?

**Comment by tyler-dane** [comment]
Hey @DiegoMutre  thanks for your interest. I'm honestly not sure about an easy way to reproduce it consistently. 

The pain ways would be to:
1. Mock the Supertokens service, returning a 401
2. Or manually expiring a supertokens session

Since there's a lot of unknowns here, the best way might be to just reach out to the Supertokens support team on Discord, which is pretty responsive with stuff like this. They'd know more than I about how to fix this.

**Comment by DiegoMutre** [comment]
Hey @tyler-dane! I haven't tried any of the ways you suggested me yet, but I tried something else: I set the access_token_validity to 60 seconds and the refresh_token_validity to 2 minutes in the SuperTokens Development Environment Configuration

![image](https://github.com/user-attachments/assets/2481cf80-2f98-4012-84f1-dcb28dca6fda)
![image](https://github.com/user-attachments/assets/4ff4e040-1037-45ef-b5de-78a77e4aae16)

So, I got the session to "expire" because it logs me out after the 2 minutes, but the issue doesn't happen, even if the account was just created.
Btw, I can't remember the default values for access_token_validity and refresh_token_validity because the change took effect the next day, but I remember that the default time for refresh token validity was around a year or more (in minutes).
However, I think on trying in the production environment of the SuperTokens to see what happen.

Anyway, I will try to reach out to the SuperTokens support team on Discord to get more info. You can try doing something like I did with the SuperTokens config to see if the same happens.

**Comment by tyler-dane** [comment]
Hey @DiegoMutre - that's great that you're coming up with creative ways to reproduce this.

While this issue might not occur after the method you described, I confirmed today that it still occurs in production :/ 

I updated the description with another screenshot to validate this.

**Comment by DiegoMutre** [comment]
Hey @tyler-dane  👋. I had a busy week so I didn't work on this issue, but now I'm back. I have a question about your SuperTokens production environment configuration:

* Is access_token_validity value 3600?
* Is the refresh_token_validity value 144000?
* How many days approximately pass before the session "expire" and this issue occurs?
 
The purpose of these questions is to try to prove this point: The session doesn't really expire because if refresh_token_validity has the default value (144000 minutes = 100 days) and the time this issue occurs is less than that value (< 100 days), it might mean that something else is going on, but not session expiration. Well, unless that's a feature of SuperTokens, to expire a session if it hasn't been active for a while even when the refresh token hasn't expired yet.

Btw, I still don't know how to reproduce that issue consistenly. It occured some days ago but I didn't calculate the last time I visited the app before that.

Anyway, I will keep trying to reproduce this issue, which is my objective now. Let me know anything that can help me to solve this issue 👍

**Comment by tyler-dane** [comment]
Hey @DiegoMutre - thanks for following up and providing those clarifying questions. You could definitely be right about it being a different issue entirely. I'll find those answers next time I get the chance, but it honestly isn't a high priority right now.  I also understand how this is a tough one to reproduce. 

If there's another of Compass you'd like to work on, LMK!

**Comment by tyler-dane** [comment]
Good news - after upgrading to the latest supertokens versions, I didn't run into this issue. I think this is because they increased their defaults and have changed how they're refreshing tokens.

After [enabling debug logging](https://supertokens.com/docs/thirdpartypasswordless/troubleshooting/how-to-troubleshoot), I was seeing these encouraging logs.

Will update this as I learn more. 

```bash
# PART 1 - TRYING REFRESH TOKEN

 com.supertokens {t: "2024-09-03T00:10:43.174Z", message: "refreshSession: Started", file: "/Users/ty/src/switchback/compass/node_modules/supertokens-node/lib/build/recipe/session/recipeImplementation.js:266:22" sdkVer: "16.7.1"} +0ms

  com.supertokens {t: "2024-09-03T00:10:43.779Z", message: "getInfoFromAccessToken: Returning TRY_REFRESH_TOKEN because access token validation failed - no applicable key found in the JSON Web Key Set", file: "/Users/ty/src/switchback/compass/node_modules/supertokens-node/lib/build/recipe/session/accessToken.js:190:18" sdkVer: "16.7.1"} +0ms

  com.supertokens {t: "2024-09-03T00:10:43.780Z", message: "getInfoFromAccessToken: Returning TRY_REFRESH_TOKEN because access token validation failed - no applicable key found in the JSON Web Key Set", file: "/Users/ty/src/switchback/compass/node_modules/supertokens-node/lib/build/recipe/session/accessToken.js:190:18" sdkVer: "16.7.1"} +0ms
```

```bash
# PART II - FAILED TO VERIFY ACCESS TOKEN (cuz it's expired)

  com.supertokens {t: "2024-09-03T00:10:43.784Z", message: "Sending response to client with status code: 401", file: "/Users/ty/src/switchback/compass/node_modules/supertokens-node/lib/build/utils.js:158:14" sdkVer: "16.7.1"} +0ms

  com.supertokens {t: "2024-09-03T00:10:43.786Z", message: "errorHandler: Started", file: "/Users/ty/src/switchback/compass/node_modules/supertokens-node/lib/build/supertokens.js:243:22" sdkVer: "16.7.1"} +0ms

  com.supertokens {t: "2024-09-03T00:10:43.786Z", message: "errorHandler: Error is from SuperTokens recipe. Message: Failed to verify access token", file: "/Users/ty/src/switchback/compass/node_modules/supertokens-node/lib/build/supertokens.js:245:26" sdkVer: "16.7.1"} +0ms
```

```bash
# PART III - REFRESHING

  com.supertokens {t: "2024-09-03T00:10:43.788Z", message: "errorHandler: returning TRY_REFRESH_TOKEN", file: "/Users/ty/src/switchback/compass/node_modules/supertokens-node/lib/build/recipe/session/recipe.js:115:30" sdkVer: "16.7.1"} +0ms

  com.supertokens {t: "2024-09-03T00:10:43.788Z", message: "Sending response to client with status code: 401", file: "/Users/ty/src/switchback/compass/node_modules/supertokens-node/lib/build/utils.js:158:14" sdkVer: "16.7.1"} +0ms

401 GET /api/event?start=2024-09-01T00:00:00-05:00&end=2024-09-07T23:59:59-05:00 712.261ms Tue, 03 Sep 2024 00:10:43 GMT
401 GET /api/event?someday=true&start=2024-09-01&end=2024-09-30 685.046ms Tue, 03 Sep 2024 00:10:43 GMT
  com.supertokens {t: "2024-09-03T00:10:43.804Z", message: "refreshSession: Success!", file: "/Users/ty/src/switchback/compass/node_modules/supertokens-node/lib/build/recipe/session/recipeImplementation.js:274:22" sdkVer: "16.7.1"} +0ms

```

```bash
PART IV - SUCCESS
  com.supertokens {t: "2024-09-03T00:10:44.016Z", message: "getSession: Success!", file: "/Users/ty/src/switchback/compass/node_modules/supertokens-node/lib/build/recipe/session/recipeImplementation.js:187:22" sdkVer: "16.7.1"} +0ms

  com.supertokens {t: "2024-09-03T00:10:44.017Z", message: "parseJWTWithoutSignatureVerification: version from header: 5", file: "/Users/ty/src/switchback/compass/node_modules/supertokens-node/lib/build/recipe/session/jwt.js:54:22" sdkVer: "16.7.1"} +0ms

  com.supertokens {t: "2024-09-03T00:10:44.018Z", message: "setToken: Setting access token as cookie", file: "/Users/ty/src/switchback/compass/node_modules/supertokens-node/lib/build/recipe/session/cookieAndHeaders.js:115:14" sdkVer: "16.7.1"} +0ms

  com.supertokens {t: "2024-09-03T00:10:44.046Z", message: "getSession: Success!", file: "/Users/ty/src/switchback/compass/node_modules/supertokens-node/lib/build/recipe/session/recipeImplementation.js:187:22" sdkVer: "16.7.1"} +0ms

  com.supertokens {t: "2024-09-03T00:10:44.046Z", message: "parseJWTWithoutSignatureVerification: version from header: 5", file: "/Users/ty/src/switchback/compass/node_modules/supertokens-node/lib/build/recipe/session/jwt.js:54:22" sdkVer: "16.7.1"} +0ms

  com.supertokens {t: "2024-09-03T00:10:44.047Z", message: "setToken: Setting access token as cookie", file: "/Users/ty/src/switchback/compass/node_modules/supertokens-node/lib/build/recipe/session/cookieAndHeaders.js:115:14" sdkVer: "16.7.1"} +0ms
```

**Comment by DiegoMutre** [comment]
> After upgrading to the latest supertokens versions and [enabling debug logging](https://supertokens.com/docs/thirdpartypasswordless/troubleshooting/how-to-troubleshoot), I was seeing these encouraging logs.
> 
> Currently working on upgrading the managed supertokens core so I can test in my staging environment to see its impact on this bug in real life
> 
> PS: Is access_token_validity value 3600? Yes Is the refresh_token_validity value 144000? Yes
> 
> ```shell
> # PART 1 - TRYING REFRESH TOKEN
> 
>  com.supertokens {t: "2024-09-03T00:10:43.174Z", message: "refreshSession: Started", file: "/Users/ty/src/switchback/compass/node_modules/supertokens-node/lib/build/recipe/session/recipeImplementation.js:266:22" sdkVer: "16.7.1"} +0ms
> 
>   com.supertokens {t: "2024-09-03T00:10:43.779Z", message: "getInfoFromAccessToken: Returning TRY_REFRESH_TOKEN because access token validation failed - no applicable key found in the JSON Web Key Set", file: "/Users/ty/src/switchback/compass/node_modules/supertokens-node/lib/build/recipe/session/accessToken.js:190:18" sdkVer: "16.7.1"} +0ms
> 
>   com.supertokens {t: "2024-09-03T00:10:43.780Z", message: "getInfoFromAccessToken: Returning TRY_REFRESH_TOKEN because access token validation failed - no applicable key found in the JSON Web Key Set", file: "/Users/ty/src/switchback/compass/node_modules/supertokens-node/lib/build/recipe/session/accessToken.js:190:18" sdkVer: "16.7.1"} +0ms
> ```
> 
> ```shell
> # PART II - FAILED TO VERIFY ACCESS TOKEN (cuz it's expired)
> 
>   com.supertokens {t: "2024-09-03T00:10:43.784Z", message: "Sending response to client with status code: 401", file: "/Users/ty/src/switchback/compass/node_modules/supertokens-node/lib/build/utils.js:158:14" sdkVer: "16.7.1"} +0ms
> 
>   com.supertokens {t: "2024-09-03T00:10:43.786Z", message: "errorHandler: Started", file: "/Users/ty/src/switchback/compass/node_modules/supertokens-node/lib/build/supertokens.js:243:22" sdkVer: "16.7.1"} +0ms
> 
>   com.supertokens {t: "2024-09-03T00:10:43.786Z", message: "errorHandler: Error is from SuperTokens recipe. Message: Failed to verify access token", file: "/Users/ty/src/switchback/compass/node_modules/supertokens-node/lib/build/supertokens.js:245:26" sdkVer: "16.7.1"} +0ms
> ```
> 
> ```shell
> # PART III - REFRESHING
> 
>   com.supertokens {t: "2024-09-03T00:10:43.788Z", message: "errorHandler: returning TRY_REFRESH_TOKEN", file: "/Users/ty/src/switchback/compass/node_modules/supertokens-node/lib/build/recipe/session/recipe.js:115:30" sdkVer: "16.7.1"} +0ms
> 
>   com.supertokens {t: "2024-09-03T00:10:43.788Z", message: "Sending response to client with status code: 401", file: "/Users/ty/src/switchback/compass/node_modules/supertokens-node/lib/build/utils.js:158:14" sdkVer: "16.7.1"} +0ms
> 
> 401 GET /api/event?start=2024-09-01T00:00:00-05:00&end=2024-09-07T23:59:59-05:00 712.261ms Tue, 03 Sep 2024 00:10:43 GMT
> 401 GET /api/event?someday=true&start=2024-09-01&end=2024-09-30 685.046ms Tue, 03 Sep 2024 00:10:43 GMT
>   com.supertokens {t: "2024-09-03T00:10:43.804Z", message: "refreshSession: Success!", file: "/Users/ty/src/switchback/compass/node_modules/supertokens-node/lib/build/recipe/session/recipeImplementation.js:274:22" sdkVer: "16.7.1"} +0ms
> ```
> 
> ```shell
> PART IV - SUCCESS
>   com.supertokens {t: "2024-09-03T00:10:44.016Z", message: "getSession: Success!", file: "/Users/ty/src/switchback/compass/node_modules/supertokens-node/lib/build/recipe/session/recipeImplementation.js:187:22" sdkVer: "16.7.1"} +0ms
> 
>   com.supertokens {t: "2024-09-03T00:10:44.017Z", message: "parseJWTWithoutSignatureVerification: version from header: 5", file: "/Users/ty/src/switchback/compass/node_modules/supertokens-node/lib/build/recipe/session/jwt.js:54:22" sdkVer: "16.7.1"} +0ms
> 
>   com.supertokens {t: "2024-09-03T00:10:44.018Z", message: "setToken: Setting access token as cookie", file: "/Users/ty/src/switchback/compass/node_modules/supertokens-node/lib/build/recipe/session/cookieAndHeaders.js:115:14" sdkVer: "16.7.1"} +0ms
> 
>   com.supertokens {t: "2024-09-03T00:10:44.046Z", message: "getSession: Success!", file: "/Users/ty/src/switchback/compass/node_modules/supertokens-node/lib/build/recipe/session/recipeImplementation.js:187:22" sdkVer: "16.7.1"} +0ms
> 
>   com.supertokens {t: "2024-09-03T00:10:44.046Z", message: "parseJWTWithoutSignatureVerification: version from header: 5", file: "/Users/ty/src/switchback/compass/node_modules/supertokens-node/lib/build/recipe/session/jwt.js:54:22" sdkVer: "16.7.1"} +0ms
> 
>   com.supertokens {t: "2024-09-03T00:10:44.047Z", message: "setToken: Setting access token as cookie", file: "/Users/ty/src/switchback/compass/node_modules/supertokens-node/lib/build/recipe/session/cookieAndHeaders.js:115:14" sdkVer: "16.7.1"} +0ms
> ```

Well, I've been out for a while because of many things in my life (university, moving, etc). I will take a look at this and try to understand what's going on. Also, I think I can work on another issue, I'll be very happy.

**Comment by tyler-dane** [comment]
No worries, @DiegoMutre. I'll keep chipping away at this and update what I find here.
Hope you're enjoying university and your new place.

**Comment by tyler-dane** [comment]
Finally figured out what's happening here. Updated the description and put this on my near-term todo list.

**Comment by tyler-dane** [comment]
Merged & deployed fix. It's difficult to be completely sure that the fix worked, so let's keep an eye on this and update things here if the behavior continues.
